apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: propeller-leader-election-rolebinding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: propeller-leader-election-role
subjects:
  - kind: ServiceAccount
    name: propeller-operator
    namespace: system
